name: Release
run-name: Relase on ${{ github.ref }}

on:
  push

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        shell: bash
        run: |
          echo "Hello, World!"
