name: Release

on:
  push

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Version
        shell: bash
        run: |
          echo "Bumping Version"
          sleep 10

  create-release:
    needs: [bump]
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            arch: x64
          - platform: macos
            os: macos-latest
            arch: aarch64
          - platform: windows
            os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build ${{ matrix.platform }}-${{ matrix.arch }}
        shell: bash
        run: |
          echo "Building ${{ matrix.platform }}-${{ matrix.arch }}"

  build:
    runs-on: ubuntu-latest
    needs: [bump]
    steps:
      - name: "Build"
        shell: bash
        run: |
          cargo_version=$(cargo --version)
          echo "Cargo Version: $cargo_version"
          sleep 10


