name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Version Bump Level'
        type: choice
        required: false
        default: patch
        options:
          - major
          - minor
          - patch

permissions: write-all

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.capture.outputs.version }}
    steps:
      - name: Install cargo-workspaces
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-workspaces

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump Version
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cargo workspaces version ${{ inputs.level }} -y --allow-branch main -m "Release %v [skip ci]" --no-individual-tags --force '*'

      - name: Capture Version
        id: capture
        shell: bash
        run: |
          version=$(cargo workspaces list --json | jq '.[0].version' -r)
          echo "Release Version: v{$version}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ needs.pre-release.outputs.version }}
        run: gh release create v${version} --draft --verify-tag --title v${version}


  build:
    name: Build ${{ matrix.platform }}-${{ matrix.arch }}
    needs: [pre-release]
    strategy:
      fail-fast: true
      matrix:
        binary: [actions-playground]
        include:
          - platform: linux
            os: ubuntu-latest
            arch: x86_64
          - platform: macos
            os: macos-latest
            arch: aarch64
          - platform: windows
            os: windows-latest
            arch: x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.pre-release.outputs.version }}
      - name: Build ${{ matrix.platform }}-${{ matrix.arch }}
        shell: bash
        run: |
          echo "Building ${{ matrix.platform }}-${{ matrix.arch }}"

  post-release:
    name: Post Release
    runs-on: ubuntu-latest
    needs: [pre-release, build]
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.pre-release.outputs.version }}
      - name: Finalize Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ needs.pre-release.outputs.version }}
        shell: bash
        run: gh release edit v${version} --draft=false --latest

