name: Release

on:
  push:
  workflow_dispatch:
    inputs:
      level:
        description: 'The level to bump for the release'
        type: choice
        required: false
        default: patch
        options:
          - major
          - minor
          - patch

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-workspaces
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-workspaces

      - name: Bump Version
        if: github.ref == 'refs/heads/main'
        run: |
          cargo release version ${{ inputs.level }} -x --no-confirm
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[skip ci] Bump Version"
          git push
      - name: Bump Version
        shell: bash
        run: |
          echo "Bumping Version"
          sleep 10
          version=$(cargo workspaces list --json | jq '.[0].version')

  create-release:
    runs-on: ubuntu-latest
    needs: [bump]
    steps:
      - name: "Build"
        shell: bash
        run: |
          cargo_version=$(cargo --version)
          echo "Cargo Version: $cargo_version"
          sleep 10

  build:
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    needs: [bump]
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            arch: x86_64
          - platform: macos
            os: macos-latest
            arch: aarch64
          - platform: windows
            os: windows-latest
            arch: x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build ${{ matrix.platform }}-${{ matrix.arch }}
        shell: bash
        run: |
          echo "Building ${{ matrix.platform }}-${{ matrix.arch }}"


