name: Release

on:
  workflow_dispatch:
    inputs:
      level:
        description: 'Version Bump Level'
        type: choice
        required: false
        default: patch
        options:
          - major
          - minor
          - patch

permissions: write-all

env:
  BINARY_NAME: actions-playground
  DOWNLOAD_PREFIX: https://github.com/archetect/archetect/releases

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.capture.outputs.version }}
    steps:
      - name: Install cargo-workspaces
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-workspaces

      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump Version
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cargo workspaces version ${{ inputs.level }} -y --allow-branch main -m "Release %v [skip ci]" --no-individual-tags --force '*'

      - name: Capture Version
        id: capture
        shell: bash
        run: |
          version=$(cargo workspaces list --json | jq '.[0].version' -r)
          echo "Release Version: v{$version}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.capture.outputs.version }}
        run: gh release create v${version} --draft --verify-tag --title v${version}


  build:
    name: Build ${{ matrix.platform }}-${{ matrix.arch }}
    needs: [pre-release]
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            arch: x86_64
          - platform: macos
            os: macos-latest
            arch: aarch64
          - platform: windows
            os: windows-latest
            arch: x86_64

    outputs:
      linux-x86_64_sha256: ${{ steps.nix_upload.outputs.linux-x86_64_sha256 }}
      linux-x86_64_artifact: ${{ steps.nix_upload.outputs.linux-x86_64_artifact }}
      macos-arm64_sha256: ${{ steps.nix_upload.outputs.darwin-arm64_sha256 }}
      macos-arm64_artifact: ${{ steps.nix_upload.outputs.darwin-arm64_artifact }}
      macos-x86_64_sha256: ${{ steps.nix_upload.outputs.darwin-x86_64_sha256 }}
      macos-x86_64_artifact: ${{ steps.nix_upload.outputs.darwin-x86_64_artifact }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.pre-release.outputs.version }}

      - name: Build ${{ matrix.platform }}-${{ matrix.arch }}
        shell: bash
        run: |
          echo "Building ${BINARY_NAME} for ${{ matrix.platform }}-${{ matrix.arch }}"

      - name: Enable Rust Dependency Caching
        uses: Swatinem/rust-cache@v2 

      - name: Build Binary
        shell: bash
        run: |
          cargo build --release
          if [ "${{ matrix.platform }}" = "windows" ]; then
            binary_path="target/release/${BINARY_NAME}.exe"
          else
            binary_path="target/release/${BINARY_NAME}"
          fi
          echo "BINARY_PATH=$binary_path" >> $GITHUB_ENV

      - name: Strip Binary
        if: matrix.platform == 'linux' || matrix.platform == 'macos'
        run: strip "$BINARY_PATH"

      - name: Create Archive
        shell: bash
        run: |
          version="v${{ needs.pre-release.outputs.version }}"
          archive_prefix="${BINARY_NAME}-${version}-${{matrix.platform}}-${{matrix.arch}}"
          mkdir -p "${archive_prefix}" >> $GITHUB_ENV
          cp "$BINARY_PATH" "$archive_prefix"
          if [ "${{ matrix.platform }}" = "windows" ]; then
            archive=${archive_prefix}.zip
            archive_sum=${archive_prefix}.zip.sha256
            7z a "${archive}" "${archive_prefix}"
            certutil -hashfile "${archive}" SHA256 > "${archive_sum}"
          else
            archive=${archive_prefix}.tar.gz
            archive_sum=${archive_prefix}.tar.gz.sha256
            tar czf "${archive}" "${archive_prefix}"
            shasum -a 256 "${archive}" > "${archive_sum}"
            echo "${{ matrix.platform }}-${{ matrix.arch}}_artifact=$DOWNLOAD_PREFIX/${version}/${archive}" >> $GITHUB_OUTPUT
            echo "${{ matrix.platform }}-${{ matrix.arch}}_sha256=$(cat $archive_sum | awk '{print $NF}')" >> $GITHUB_OUTPUT
          fi          
          echo "ARCHIVE=${archive}" >> $GITHUB_ENV
          echo "ARCHIVE_SUM=${archive_sum}" >> $GITHUB_ENV

      - name: Upload Release Archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          version="${{ needs.pre-release.outputs.version }}"
          gh release upload v"$version" "${ARCHIVE}" "${ARCHIVE_SUM}"


  post-release:
    name: Post Release
    runs-on: ubuntu-latest
    needs: [pre-release, build]
    steps:
      - name: Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: v${{ needs.pre-release.outputs.version }}
      - name: Finalize Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ needs.pre-release.outputs.version }}
        shell: bash
        run: gh release edit v${version} --draft=false --latest

  update_homebrew_formula:
    name: Update Homebrew Forumula
    needs: [pre-release, build]
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch event to jimmiebfulton/homebrew-tap
        uses: ph-fritsche/action-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type: repository
          repo: jimmiebfulton/homebrew-tap
          ident: update-formula
          payload: |
            {
              "name": "actions-playground",
              "description: "Actions Playground CLI",
              "homepage: "example.com",
              "version": "${{ needs.pre-release.outputs.version }}",
              "linux-x86_64_archive": "${{ needs.build.outputs.linux-x86_64_archive }}",
              "linux-x86_64_sha256": "${{ needs.build.outputs.linux-x86_64_sha256 }}",
              "macos-arm64_archive": "${{ needs.build.outputs.macos-arm64_archive }}",
              "macos-arm64_sha256": "${{ needs.build.outputs.macos-arm64_sha256 }}",
            }
